export const FETCH_CATALOG_ITEMS = "FETCH_CATALOG_ITEMS";
export const FETCH_CATALOG_ITEMS_SUCCESS = "FETCH_CATALOG_ITEMS_SUCCESS";
export const FETCH_CATALOG_ITEMS_ERROR = "FETCH_CATALOG_ITEMS_ERROR";
export const ADD_ITEM_CATALOG_ITEMS = "ADD_ITEM_CATALOG_ITEMS";
export const REMOVE_ITEM_CATALOG_ITEMS = "REMOVE_ITEM_CATALOG_ITEMS";
export const GET_ITEM_CATALOG_ITEMS = "GET_ITEM_CATALOG_ITEMS";
